---
language: php

php:
  - 5.6
  - 7.0

addons:
  apt:
    packages:
    - rubygem-sass
    - imagemagick
    - make

install:
  - composer install

script:
  - php vendor/bin/phpcs --standard=psr2 --ignore=vendor -n .
  - ./bin/2srt2ssa --main example/example_en.srt --alt example/example_it.srt

